### ISSUE TITLE
lrreload error on paper 1.18.1 

### ISSUE THREAD

**Issue by M2tecDev** [zhenghanlee/LargeRaids#1]
[20:24:43] [Server thread/WARN]: Unexpected exception while parsing console command "lrreload"
org.bukkit.command.CommandException: Cannot execute command 'lrreload' in plugin LargeRaids v1.8.2 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897) ~[paper-1.18.1.jar:git-Paper-101]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchServerCommand(CraftServer.java:860) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:507) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:481) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-101]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by solarrabbit99** [comment]
@M2tecDev Hi there, this is most probably due to changes in the `config.yml`. Refer to [this page](https://www.spigotmc.org/resources/largeraids-1-14-x-1-18-x.95422/updates) for the updates since the past version you have used. The easiest remedy is to back up the old `config.yml` and restart/reload the server to allow the plugin to create a new `config.yml` file.

**Comment by solarrabbit99** [comment]
Closing issue for now, you may reopen the issue if the problem persists
