### ISSUE TITLE
1.18.2 Not loading

### ISSUE THREAD

**Issue by PaladinFallen** [zhenghanlee/LargeRaids#3]
1:44:58] [Server thread/INFO]: [LargeRaids] Enabling LargeRaids v1.10
[21:44:58] [Server thread/ERROR]: Error occurred while enabling LargeRaids v1.10 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.solarrabbit.largeraids.PluginLogger.sendMessage(String, com.solarrabbit.largeraids.PluginLogger$Level)" because "this.logger" is null
	at com.solarrabbit.largeraids.LargeRaids.log(LargeRaids.java:93) ~[LargeRaids.jar:?]
	at com.solarrabbit.largeraids.LargeRaids.verifyServerVersion(LargeRaids.java:221) ~[LargeRaids.jar:?]
	at com.solarrabbit.largeraids.LargeRaids.onEnable(LargeRaids.java:61) ~[LargeRaids.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-230]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-230]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[paper-1.18.2.jar:git-Paper-230]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.18.2.jar:git-Paper-230]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-230]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1165) ~[paper-1.18.2.jar:git-Paper-230]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-230]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:44:58] [Server thread/INFO]: [LargeRaids] Disabling LargeRaids v1.10
[21:44:58] [Server thread/ERROR]: Error occurred while disabling LargeRaids v1.10 (Is it up to date?)
java.lang.NullPointerException: Cannot read field "currentRaids" because "this.raidManager" is null
	at com.solarrabbit.largeraids.LargeRaids.onDisable(LargeRaids.java:88) ~[LargeRaids.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-230]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-230]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[paper-1.18.2.jar:git-Paper-230]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.18.2.jar:git-Paper-230]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-230]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1165) ~[paper-1.18.2.jar:git-Paper-230]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-230]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by solarrabbit99** [comment]
Sorry for late reply, but the plugin isn't yet ready for 1.18.2. I will be updating it soon.
